name = "cdn-tf"
account_id = '2ebd873bcedc1f859e972e90f72ed22b'
compatibility_flags = []
compatibility_date = "2022-03-15"
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "0242d53e756f415a8d66466ceda8279d", id= "746fa4dc493f4cd8b8a96b851ab6ab05" },
]
workers_dev = true
[vars]
BASEPLATE_ENV = "prod"
# [secrets]
# S3_PROXY_REGION
# S3_PROXY_ACCESS_KEY_ID
# S3_PROXY_SECRET_ACCESS_KEY

[env.dev]
workers_dev = true
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "7106ba150d064133b762c66b692366c2", id= "8bb8422a55f9400392b030c15c87d534" },
]
[env.dev.vars]
BASEPLATE_ENV = "dev"

[env.test]
workers_dev = true
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "7b65b182bacd458e8a0f76aad7dd064d", id= "fb6b711cd9bf403a9db725c4a0fceb5b" },
]
[env.test.vars]
BASEPLATE_ENV = "test"
