name = "single-spa-foundry-worker"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-11-11"
webpack_config = "webpack.config.cjs"