name = "cdn-tf-worker"
main = "src/main.ts"
account_id = '2ebd873bcedc1f859e972e90f72ed22b'
compatibility_flags = []
compatibility_date = "2022-03-15"
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "c85c67a045a7494ca6e1660d0a07a1f5", id = "c85c67a045a7494ca6e1660d0a07a1f5" },
]
workers_dev = true
rules = [
  { type = "Text", globs = ["**/*.mustache"], fallthrough = true }
]
[vars]
BASEPLATE_ENV = "prod"
# [secrets]
# AWS_REGION
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# TIMESTREAM_DATABASE
# TIMESTREAM_TABLE

[env.dev]
workers_dev = true
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "8bb8422a55f9400392b030c15c87d534", id = "8bb8422a55f9400392b030c15c87d534" },
]
[env.dev.vars]
BASEPLATE_ENV = "dev"

[env.test]
workers_dev = true
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "2a5cc6c2ae8d46eeb0f728f091410a54", id = "2a5cc6c2ae8d46eeb0f728f091410a54" },
]
[env.test.vars]
BASEPLATE_ENV = "test"
