name = "cdn"
account_id = '4e3c47217c0159e8dfb0da2f736bf59f'
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
compatibility_date = "2022-03-15"
webpack_config = "webpack.config.cjs"
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "44604b1242bb4fb3ab5bd7805bd37da1", id= "2ff77f2cdf2348049659b8e8084773cf" },
]
workers_dev = true
[vars]
FOUNDRY_ENV = "prod"
# [secrets]
# S3_PROXY_REGION
# S3_PROXY_ACCESS_KEY_ID
# S3_PROXY_SECRET_ACCESS_KEY

[env.dev]
workers_dev = true
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "f94ad3b9def34b51bd20677f6264c6d3", id= "a048040130494df881efc89784aa3d69" },
]
[env.dev.vars]
FOUNDRY_ENV = "dev"

[env.test]
workers_dev = true
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "0094ff00faf944b29ea2285756dca341", id= "3843295ae4004f2db131aa7ecda3d005" },
]
[env.test.vars]
FOUNDRY_ENV = "test"
