name = "single-spa-foundry-worker"
account_id = '4e3c47217c0159e8dfb0da2f736bf59f'
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-11-11"
webpack_config = "webpack.config.cjs"
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "e494f429e91b43b09a28fb2473ccdebe", id= "e494f429e91b43b09a28fb2473ccdebe" },
]

[vars]
FOUNDRY_ENV = "prod"

# TODO: swap this to be a bucket/server that's actually for foundry. This is just a placeholder
FOUNDRY_MFE_HOST = "https://react.microfrontends.app/"

[env.dev]
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "e494f429e91b43b09a28fb2473ccdebe", id= "e494f429e91b43b09a28fb2473ccdebe" },
]
[env.dev.vars]
FOUNDRY_ENV = "dev"

[env.test]
kv_namespaces = [ 
  { binding = "MAIN_KV", preview_id = "e494f429e91b43b09a28fb2473ccdebe", id= "e494f429e91b43b09a28fb2473ccdebe" },
]
[env.test.vars]
FOUNDRY_ENV = "test"
