name: CI/CD
on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
    secrets:
      CF_API_TOKEN:
        required: true
jobs:
  deploy:
    name: Deploy to Cloudflare environment
    environment: ${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - uses: pnpm/action-setup@v2
        with:
          version: 7.27.0
      - run: pnpm install --frozen-lockfile
      - name: Deploy to Cloudflare
        run: |
          if [[ "${{ inputs.envName }}" == "prod" ]]
          then
            echo "Deploying prod"
            pnpm exec wrangler publish
          else
            echo "Deploying ${{ inputs.envName }}"
            pnpm exec wrangler publish --env ${{ inputs.envName }}
          fi
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
