name: CI/CD
on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
      secrets:
        cfApiToken:
          required: true
        cfAccountId:
          required: true
jobs:
  deploy:
    name: Deploy to Cloudflare environment
    environment: ${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.cfApiToken }}
          environment: ${{ inputs.envName }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.cfAccountId }}
