name: CI/CD
on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
    secrets:
      CF_API_TOKEN:
        required: true
jobs:
  deploy:
    name: Deploy to Cloudflare environment
    environment: ${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
      - run: pnpm install --frozen-lockfile
      - name: Deploy to Cloudflare
        run: pnpm exec wrangler publish --env ${{ inputs.envName }}
