name: CI/CD
on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
      secrets:
        cloudflare-api-token:
          required: true
        cloudflare-account-id:
          required: true
jobs:
  deploy:
    name: Deploy to Cloudflare environment
    environment: ${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.cloudflare-api-token }}
          environment: ${{ inputs.envName }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.cloudflare-account-id }}
