name: CI/CD
on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
    secrets:
      CF_API_TOKEN:
        required: true
jobs:
  deploy:
    name: Deploy to Cloudflare environment
    environment: ${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: ${{ inputs.envName }}
