name: Release New Tag
on:
  release:
    types: [published]
jobs:
  deploy-test:
    uses: JustUtahCoders/baseplate-cloudflare-worker/.github/workflows/deploy.yaml@main
    with:
      envName: test
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  deploy-prod:
    needs: deploy-test
    uses: JustUtahCoders/baseplate-cloudflare-worker/.github/workflows/deploy.yaml@main
    with:
      envName: prod
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
